version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_poc
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Poc_Senha_123!
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: